### ISSUE TITLE
New Name

### ISSUE THREAD

**Issue by CheezBallzPi** [RoboEagles4828/2018Robot#22]
Robot's new name is Basteel.

We're gonna have to update everything, and it's gonna be a royal pain, so have @tamablevirus do it or something.

**Comment by CheezBallzPi** [comment]
That was a joke, I'll probably do it.

**Comment by jacksondm33** [comment]
ctrl + H:
Find: 2018Robot
Replace: Basteel

**Comment by jacksondm33** [comment]
What is there to change?

**Comment by CheezBallzPi** [comment]
Your repos have to be reset
URL changed

**Comment by jacksondm33** [comment]
I just deleted the directory and recloned with the new url.

**Comment by CheezBallzPi** [comment]
Yeah, but ya gotta do that on the shop computer.

**Comment by jacksondm33** [comment]
Ok, I just didn't know if there were any other files to change.
I have already fixed the settings.gradle and README file which should be all.
